name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: The tag of the release you want to append the artifact to
        required: true


jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6

      - name: 'Display current branch/tag name'
        run: echo ${{ github.ref_name }}

      - id: setmatrix
        uses: JoshuaTheMiller/conditional-build-matrix@v2.0.1
        with:
          # inputFile: '.github/workflows/matrix_includes.json' # Default input file path
          filter: '[? `${{ github.event_name }}` == `release` || `${{ github.ref_name }}` == branch]'

      - name: 'Print matrix'
        run: echo ${{ steps.setmatrix.outputs.matrix }}

  release:
    needs: matrix_prep
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ matrix.branch }}
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev' }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
        env:
          BUILD_RELEASE: true

      - name: Upload to action artifact
        uses: actions/upload-artifact@v6
        with:
          name: '[${{ matrix.branch }}] build-artifacts'
          path: build/libs/

      - name: Get github release information
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: get_release
        uses: cardinalby/git-get-release-action@1.2.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event.inputs.target_release_tag }}

      - name: Generate publish related infomation
        id: release_info
        run: |
          if [ $GITHUB_EVENT_NAME == 'release' ]
          then
              echo "::set-output name=tag_name::"  # leave an empty value here so softprops/action-gh-release will use the default value
          elif [ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]
          then
              echo "::set-output name=tag_name::${{ github.event.inputs.target_release_tag }}"
          else
              echo Unknown github event name $GITHUB_EVENT_NAME
              exit 1
          fi

      - name: Read common properties
        id: properties_g
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: gradle.properties
          all: true

      - name: Publish Minecraft Mods
        uses: Kira-NT/mc-publish@v3.3
        with:
          modrinth-id: _INSERT_MODRITH_MOD_ID_HERE_
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          curseforge-id: _INSERT_CURSEFORGE_MOD_ID_HERE_
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          github-tag: ${{ steps.release_info.outputs.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: ''

          name: ${{ format('FabricModTemplate v{0} for mc{1}', steps.properties_g.outputs.mod_version, steps.properties_g.outputs.minecraft_version) }}
          version: ${{ format('mc{0}-v{1}', steps.properties_g.outputs.minecraft_version, steps.properties_g.outputs.mod_version) }}
          version-type: release
          changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}  # one of them should be an empty string (null)

          loaders: fabric
          game-versions: ${{ matrix.game_versions }}
          version-resolver: exact

          retry-attempts: 3
          retry-delay: 10000
